apiVersion: v1
kind: ConfigMap
metadata:
  name: fraeym-crud-env-data
  namespace: {{ .Release.Namespace }}
data:
  .env: |
    {{- if .Values.debug | default .Values.global.debug }}
    APP_ENV=development
    LOG_LEVEL=debug
    {{- else }}
    APP_ENV=production
    LOG_LEVEL=info
    LOG_FORMAT=json
    {{- end }}
    
    HTTP_REQUEST_BODY_LIMIT=10
    CORS_ALLOW_ORIGINS=*

    SYNC_CLIENT_ADDRESS=sync.{{ .Release.Namespace }}.svc.cluster.local:9000
    SYNC_CLIENT_APP_PREFIX=crud

    STREAMS_CLIENT_ADDRESS=streams.{{ .Release.Namespace }}.svc.cluster.local:9000
    STREAMS_CLIENT_GROUP_ID=crud

    PROJECTIONS_CLIENT_ADDRESS=projections.{{ .Release.Namespace }}.svc.cluster.local:9000

    IMGPROXY_URL=http://fraeym-imgproxy.{{ .Release.Namespace }}.svc.cluster.local

    S3_BUCKET={{ .Values.s3.bucket | default .Values.global.s3.bucket }}
    S3_ENDPOINT={{ .Values.s3.endpoint | default .Values.global.s3.endpoint }}
    S3_SSL={{ .Values.s3.ssl | default .Values.global.s3.ssl }}
