apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud
  namespace: {{ .Release.Namespace }}
  labels:
    app: crud
  annotations:
    secret.reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
        linkerd.io/inject: enabled
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: env
          configMap:
            name: fraeym-crud-env-data
      imagePullSecrets:
        - name: fraeym-crud-dockerconfigjson
      containers:
        - name: crud
          image: {{ .Values.image }}:v{{ .Values.version }}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: fraeym-crud-config
            - secretRef:
                name: fraeym-crud-s3-config
            - secretRef:
                name: fraeym-crud-postgresql-config
          ports:
            - containerPort: 3000
            - containerPort: 3001
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: env
              mountPath: /.env
              subPath: .env
              readOnly: true
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              {{- if .Values.resources.limits.cpu }}
              cpu: {{ .Values.resources.limits.cpu }}
              {{- end }}
