apiVersion: v1
kind: Secret
metadata:
  name: fraeym-crud-config
  namespace: {{ .Release.Namespace }}
data:
  AUTH_SECRET: {{ (.Values.auth.secret | default .Values.global.auth.secret) | b64enc }}
  POSTGRES_CONNECTION: {{ (.Values.postgres.connection | default .Values.global.postgres.connection) | b64enc }}
  S3_ACCESS_KEY: {{ (.Values.s3.accessKeyId | default .Values.global.s3.accessKeyId) | b64enc }}
  S3_SECRET_KEY: {{ (.Values.s3.secretAccessKey | default .Values.global.s3.secretAccessKey) | b64enc }}
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: fraeym-crud-dockerconfigjson
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ include "fraeym.dockerconfig" . }}
