apiVersion: v1
kind: Secret
metadata:
  name: fraeym-crud-s3-config
  namespace: {{ .Release.Namespace }}
data:
  S3_ACCESS_KEY: {{ .Values.s3.accessKeyId | b64enc }}
  S3_ENDPOINT: {{ .Values.s3.endpoint | b64enc }}
  S3_SECRET_KEY: {{ .Values.s3.secretAccessKey | b64enc }}
  S3_SSL: {{ .Values.s3.ssl | default "false" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: fraeym-crud-postgresql-config
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_CONNECTION: {{ .Values.postgres.connection | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: fraeym-crud-config
  namespace: {{ .Release.Namespace }}
data:
  AUTH_SECRET: {{ .Values.auth.secret | b64enc }}
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: fraeym-crud-dockerconfigjson
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ include "fraeym.dockerconfig" . }}
