apiVersion: v2
name: crud
description: "Fraeym CRUD: Easily create a CRUD API for your data"
type: application
version: 1.2.0-alpha.1 # Chart version
appVersion: "1.2.0-alpha.1" # Fraeym CRUD version
