apiVersion: v1
kind: ConfigMap
metadata:
  name: fraeym-auth-env-data
  namespace: {{ .Release.Namespace }}
data:
  .env: |
    {{- if .Values.debug }}
    APP_ENV=development
    LOG_LEVEL=debug
    {{- else }}
    APP_ENV=production
    LOG_LEVEL=info
    LOG_FORMAT=json
    {{- end }}
    
    CORS_ALLOW_ORIGINS=*

    SYNC_CLIENT_ADDRESS=sync.{{ .Release.Namespace }}.svc.cluster.local:9000
    SYNC_CLIENT_APP_PREFIX=auth

    STREAMS_CLIENT_ADDRESS=streams.{{ .Release.Namespace }}.svc.cluster.local:9000
    STREAMS_CLIENT_GROUP_ID=auth

    CRUD_CLIENT_ADDRESS=crud.{{ .Release.Namespace }}.svc.cluster.local:9000

    DEPLOYMENTS_CLIENT_ADDRESS=deployments.{{ .Release.Namespace }}.svc.cluster.local:9000
    DEPLOYMENTS_NAMESPACE=FraymAuth
