apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth
  annotations:
    secret.reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
        linkerd.io/inject: enabled
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: env
          configMap:
            name: fraeym-auth-env-data
      initContainers:
        - name: wait-for-dependencies
          image: ghcr.io/groundnuty/k8s-wait-for:v1.6
          imagePullPolicy: IfNotPresent
          args:
            - "pod"
            - "-lapp in (sync, streams, crud, deployments)"
      containers:
        - name: auth
          image: {{ .Values.image }}:v{{ .Values.version }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: {{ .Values.secretName.auth }}
          ports:
            - containerPort: 3000
            - containerPort: 3001
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: env
              mountPath: /.env
              subPath: .env
              readOnly: true
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              {{- if .Values.resources.limits.cpu }}
              cpu: {{ .Values.resources.limits.cpu }}
              {{- end }}
      imagePullSecrets:
        - name: fraeym-ghcr-cred
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: auth
                topologyKey: "kubernetes.io/hostname"
