apiVersion: v1
kind: Secret
metadata:
  name: fraeym-deployments-config
data:
  API_TOKEN: {{ .Values.apiToken | b64enc }}
  POSTGRES_CONNECTION: {{ .Values.postgres.connection | b64enc }}
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: fraeym-deployments-dockerconfigjson
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ include "fraeym.dockerconfig" . }}
