apiVersion: v1
kind: ConfigMap
metadata:
  name: fraeym-sync-env-data
  namespace: {{ .Release.Namespace }}
data:
  .env: |
    {{- if .Values.debug | default .Values.global.debug }}
    APP_ENV=development
    LOG_LEVEL=debug
    {{- else }}
    APP_ENV=production
    LOG_LEVEL=info
    LOG_FORMAT=json
    {{- end }}
