apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync
  namespace: {{ .Release.Namespace }}
  labels:
    app: sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sync
  template:
    metadata:
      labels:
        app: sync
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
        linkerd.io/inject: enabled
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: env
          configMap:
            name: fraeym-sync-env-data
      containers:
        - name: sync
          image: {{ .Values.image }}:v{{ .Values.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: env
              mountPath: /.env
              subPath: .env
              readOnly: true
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              {{- if .Values.resources.limits.cpu }}
              cpu: {{ .Values.resources.limits.cpu }}
              {{- end }}
      imagePullSecrets:
        - name: regcred
