kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: fraeym-sync-dockerconfigjson
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ include "fraeym.dockerconfig" . }}
