apiVersion: v1
kind: Service
metadata:
  name: sync
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: sync
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 80
      targetPort: 3000
    - name: grpc
      protocol: TCP
      appProtocol: grpc
      port: 9000
      targetPort: 9000
