apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fraeym-wait-for-binding-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fraeym-wait-for-pods
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
