apiVersion: v1
kind: ConfigMap
metadata:
  name: fraeym-streams-env-data
  namespace: {{ .Release.Namespace }}
data:
  .env: |
    APP_ENV={{ .Values.appEnv | default "development" }}
    {{- if .Values.debug }}
    LOG_LEVEL=debug
    {{- else }}
    LOG_LEVEL=info
    LOG_FORMAT=json
    {{- end }}
    
    CORS_ALLOW_ORIGINS=*
    
    SYNC_CLIENT_ADDRESS=sync.{{ .Release.Namespace }}.svc.cluster.local:9000
    SYNC_CLIENT_APP_PREFIX=streams
