{{- if .Values.overrides }}
apiVersion: v1
kind: Secret
metadata:
  name: fraeym-projections-overrides
  namespace: {{ .Release.Namespace }}
data:
  overrides.yaml: {{ .Values.overrides | toYaml | b64enc }}
{{- end }}
