{{- if .Values.overrides }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fraeym-projections-overrides
  namespace: {{ .Release.Namespace }}
data:
  overrides.yaml: | {{ .Values.overrides | nindent 4 }}
{{- end }}
