apiVersion: v1
kind: Secret
metadata:
  name: fraeym-projections-postgresql-config
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_CONNECTION: {{ .Values.postgres.connection | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: fraeym-projections-config
  namespace: {{ .Release.Namespace }}
data:
  AUTH_SECRET: {{ .Values.auth.secret | b64enc }}
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: fraeym-projections-dockerconfigjson
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ include "fraeym.dockerconfig" . }}
