apiVersion: v2
name: deployments
description: "Fraeym Deployments: Schema Deployments for Fraeym"
type: application
version: 1.2.0-alpha.5 # Chart version
appVersion: "1.2.0-alpha.5" # Fraeym Deployments version
