apiVersion: v2
name: projections
description: "Fraeym Projections: Projections for event sourced applications"
type: application
version: 1.2.0-alpha.1 # Chart version
appVersion: "1.2.0-alpha.1" # Fraeym Projections version
