global:
  debug: false
  github:
    username:
    token:
  auth:
    secret:
  postgres:
    connection:
  s3:
    ssl: false

projections:
  enabled: false

crud:
  enabled: false

deployments:
  enabled: false

auth:
  enabled: false
  initialPasswordSecret:
